blueprint:
  name: Motion detected daytime
  description: Turn on a scene for a period of time when motion is detected.
  domain: automation
  source_url: https://github.com/Wholteza/homeassistant-blueprints/blob/main/motion_detection_turn_on_scene_daytime.yaml
  input:
    motion_entity:
      name: Motion Sensor
      description: Motion sensor entity to trigger on
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    scene_active_target:
      name: Active scene
      description: Scene that gets turned on by the motion sensor
      selector:
        entity:
          domain: scene
    scene_inactive_target:
      name: Inactive scene
      description: Scene that gets restored after the delay time period
      selector:
        entity:
          domain: scene
    daytime_boolean_entity:
      name: Is daytime boolean
      description: Entity that states if it is daytime or not
      default: input_boolean.isdaytime
      selector:
        entity:
          domain: input_boolean
    automation_active_boolean_entity:
      name: Is automation activated boolean
      description: Entity that states if automation should be run or not
      selector:
        entity:
          domain: input_boolean

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: !input daytime_boolean_entity
      state: 'on'
    - condition: state
      entity_id: !input automation_active_boolean_entity
      state: 'on'

action:
  - data:
      entity_id: !input scene_active_target
    service: scene.turn_on

  - delay: '00:05:00'

  - data:
      entity_id: !input scene_inactive_target
    service: scene.turn_on
